
services:
  fastapi:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
